# code from https://www.youtube.com/watch?v=Zd014DjonqE
# https://cloud.google.com/build/docs/build-config-file-schema

steps:
# Install
- name: 'gcr.io/cloud-builders/yarn'
  args: ['add', 'package.json']
  dir: './dummy-react-app'

# Test
- name: 'gcr.io/cloud-builders/yarn'
  args: ['test']
  dir: './dummy-react-app'

# Build
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']
  dir: './dummy-react-app'