# code from https://www.youtube.com/watch?v=Zd014DjonqE
# https://cloud.google.com/build/docs/build-config-file-schema

steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: './dummy-react-app'

# Test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']
  dir: './dummy-react-app'

# Build
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: './dummy-react-app'